# Generated by Django 5.0.4 on 2024-05-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoblinMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goblin_id', models.IntegerField()),
                ('hostname', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('os_version', models.CharField(max_length=100)),
                ('architecture', models.CharField(max_length=100)),
                ('process', models.CharField(max_length=100)),
                ('process_id', models.CharField(max_length=100)),
                ('integrity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GoblinTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('arguments', models.JSONField(blank=True, null=True)),
                ('file', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Listener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Goblin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('last_seen', models.DateTimeField(null=True)),
                ('metadata', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goblin', to='teamserver.goblinmetadata')),
                ('tasks', models.ManyToManyField(blank=True, related_name='assigned_goblins', to='teamserver.goblintask')),
            ],
        ),
        migrations.CreateModel(
            name='GoblinTaskResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=100)),
                ('task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='teamserver.goblintask')),
            ],
        ),
        migrations.CreateModel(
            name='HttpListener',
            fields=[
                ('listener_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='teamserver.listener')),
                ('port', models.IntegerField()),
            ],
            bases=('teamserver.listener',),
        ),
    ]
