# Generated by Django 5.0.4 on 2024-05-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goblintask',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
