# Generated by Django 5.0.4 on 2024-05-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamserver', '0002_alter_goblintask_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='goblintask',
            name='is_pending',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='goblintask',
            name='command',
            field=models.CharField(choices=[('ps', 'Process List')], max_length=50),
        ),
    ]
